# Liste de mots français courants pour le générateur de mots croisés
# Cette liste contient environ 5000 mots courants triés par longueur décroissante

FRENCH_WORDS = [
    # Mots très longs (12+ lettres)
    "gouvernement", "particulierement", "developpement", "administration", "transformation",
    "communication", "responsabilite", "representation", "interpretation", "environnement",
    "etablissement", "comportement", "fonctionnement", "investissement", "professionnel",
    "international", "exceptionnelle", "supplementaire", "caracteristique", "reconnaissance",
    "independance", "connaissance", "apprentissage", "accompagnement", "renseignement",
    "manifestation", "demonstration", "organisation", "acceleration", "determination",
    "appreciation", "augmentation", "concentration", "construction", "contribution",
    "conversation", "coordination", "decouverte", "distribution", "documentation",
    
    # Mots longs (9-11 lettres)
    "absolument", "acceptable", "accessible", "accompagne", "accueil",
    "admiration", "adolescent", "adventure", "affirmatif", "agriculture",
    "alimentation", "alternative", "ambassadeur", "amelioration", "americain",
    "appartement", "application", "appreciation", "architecture", "atmosphere",
    "authentique", "automatique", "automobile", "bibliotheque", "bienvenue",
    "bouteille", "brillante", "calculatrice", "campagne", "capitaine",
    "catastrophe", "celebration", "centimetre", "certainement", "chaleureux",
    "champignon", "changement", "chaussure", "chevalier", "chocolat",
    "circulation", "collection", "combinaison", "commandant", "commentaire",
    "compagnie", "comparaison", "competition", "complement", "complique",
    "composition", "comprehension", "comptable", "conception", "concurrence",
    "conference", "confiance", "confusion", "conscience", "consequence",
    "conservation", "considerable", "construction", "consultation", "contenu",
    "continent", "continuation", "contraire", "contribution", "convention",
    "conviction", "cooperation", "correction", "couverture", "croissance",
    "dangereux", "decembre", "decoration", "definition", "delicieux",
    "democratie", "departement", "dependance", "depression", "descendant",
    "description", "desespoir", "dessiner", "destination", "destruction",
    "difference", "difficile", "direction", "discipline", "discussion",
    "disponible", "distinction", "docteur", "domestique", "economique",
    "education", "efficace", "electricite", "elephant", "emission",
    "emotion", "employer", "encourager", "entreprise", "entretien",
    "enthousiaste", "environnement", "equipement", "essentiel", "estimation",
    "etonnement", "evaluation", "exactement", "exceptionnel", "exclusif",
    "execution", "exercice", "expedition", "experience", "explication",
    "exportation", "expression", "extension", "extraordinaire", "fabrication",
    "facilement", "fascination", "favorable", "feuillage", "finalement",
    "fondateur", "fondation", "formation", "formidable", "forteresse",
    "franchise", "frequence", "frontiere", "generation", "geographie",
    "gouvernement", "gratitude", "habitation", "harmonie", "historique",
    "honorable", "horizontal", "hotel", "humidite", "hypocrite",
    "ignorance", "imagination", "immediatement", "immeuble", "immigration",
    "importance", "impossible", "impression", "imprimante", "incapable",
    "independant", "indication", "industrie", "influence", "information",
    "ingredient", "initiative", "innovation", "inquietude", "inscription",
    "inspecteur", "inspiration", "installation", "instruction", "instrument",
    "intelligence", "intention", "interessant", "interieur", "interpretation",
    "intervention", "introduction", "invitation", "isolation", "jardinage",
    "journaliste", "justification", "kilometres", "laboratoire", "legislation",
    "lieutenant", "litterature", "locomotive", "magnifique", "maintenant",
    "malheureusement", "manifestation", "manipulation", "manufacture", "mathematiques",
    "mecanique", "medicament", "meilleure", "melodie", "memorable",
    "mentalite", "merveilleux", "militaire", "millionnaire", "ministere",
    "modification", "monastere", "montagne", "moustache", "mouvement",
    "multiplicateur", "municipal", "mystere", "nationalite", "naturellement",
    "navigation", "necessaire", "negligence", "negociation", "nerveux",
    "normalement", "nostalgie", "notification", "nourriture", "nouveaute",
    "objection", "obligation", "observation", "occupation", "operation",
    "opposition", "optimiste", "ordinateur", "organisation", "orientation",
    "originaire", "orphelin", "pacifique", "parapluie", "parlement",
    "participant", "particulier", "patrimoine", "peninsule", "perception",
    "perfection", "permanence", "permission", "personnage", "personnel",
    "perspective", "philosophie", "photographie", "pittoresque", "plantation",
    "plateforme", "politicien", "population", "possibilite", "pourriture",
    "pratiquement", "precipitation", "preference", "prejudice", "preparation",
    "presentation", "preservation", "president", "prevention", "principale",
    "privilege", "probablement", "problematique", "procession", "production",
    "profession", "programme", "progression", "prohibition", "projection",
    "promotion", "promptement", "prononciation", "propagande", "proportion",
    "proposition", "protection", "providence", "publication", "qualification",
    "quartier", "question", "raccourci", "radiateur", "rapidement",
    "realisation", "reception", "recherche", "recommandation", "reconnaissance",
    "recreation", "recrutement", "reduction", "reference", "reflection",
    "refrigerateur", "regional", "reglementation", "rehabilitation", "relation",
    "religieux", "remarquable", "renaissance", "rencontre", "rendement",
    "renovation", "reparation", "repertoire", "repetition", "reponse",
    "representation", "republique", "reputation", "reservation", "residence",
    "resistance", "resolution", "respectable", "responsable", "restaurant",
    "restriction", "resultat", "retirement", "revolution", "richesse",
    "ridicule", "rivalite", "sacrifice", "satisfaction", "secretaire",
    "selection", "sensation", "sentiment", "separation", "septembre",
    "serviette", "signification", "simplicite", "simulation", "situation",
    "socialiste", "solidarite", "solution", "sophistique", "souvenir",
    "specialiste", "spectaculaire", "spectateur", "spirituel", "statistique",
    "stimulation", "strategique", "structure", "subdivision", "substance",
    "substitution", "suggestion", "supplement", "surveillance", "sympathie",
    "technique", "technologie", "telegramme", "telephone", "television",
    "temperature", "tendance", "terminal", "terrible", "territoire",
    "terroriste", "testament", "theologie", "thermometre", "tolerance",
    "touriste", "tradition", "traduction", "transaction", "transcription",
    "transformation", "transition", "transmission", "transport", "tremblant",
    "tribunal", "triomphe", "tuberculose", "uniforme", "universite",
    "urbanisation", "utilisation", "vaccination", "vegetation", "vengeance",
    "ventilateur", "verification", "veterinaire", "vibration", "violoniste",
    "visibilite", "vocabulaire", "volleyball", "volontaire",
    
    # Mots moyens (6-8 lettres)
    "abandon", "abriter", "absence", "absolu", "abstrait", "accepter", "accident", "accompli",
    "accord", "accuser", "acheter", "acquis", "acteur", "action", "activite", "actuel",
    "adapter", "addition", "admettre", "adoption", "adresse", "adulte", "adverse", "affaire",
    "affirmer", "agence", "agiter", "agreable", "aider", "ailleurs", "ajouter", "alarme",
    "alcool", "alerter", "aliment", "allemand", "alliance", "allumer", "amateur", "ambiance",
    "amener", "ancien", "anglais", "angoisse", "animal", "annoncer", "annuel", "anticiper",
    "anxieux", "apercu", "appareil", "apparent", "appeler", "apporter", "apprendre", "approche",
    "approuver", "arbre", "ardeur", "argent", "argument", "armer", "arranger", "arreter",
    "arriver", "article", "artiste", "aspect", "assembler", "asseoir", "assez", "associer",
    "assurer", "attacher", "attaquer", "atteindre", "attendre", "attirer", "attitude", "attraper",
    "aucun", "audace", "audience", "augmenter", "aussitot", "autant", "auteur", "autorite",
    "autour", "autre", "avancer", "avantage", "avenir", "aventure", "avertir", "avion",
    "avoir", "avouer", "bagage", "baguette", "baigner", "baisser", "balance", "balancer",
    "balcon", "bande", "banque", "barrage", "barriere", "bataille", "bateau", "batiment",
    "battre", "beaute", "besoin", "beurre", "bien", "billet", "bizarre", "blanche",
    "blesser", "bloquer", "boire", "bonheur", "bord", "border", "bouche", "bouger",
    "bouquet", "branche", "bras", "briser", "brouillard", "bruler", "brusque", "bureau",
    "cabane", "cabinet", "cacher", "cadeau", "cadre", "cafard", "cahier", "caisse",
    "calculer", "calme", "camarade", "camera", "camion", "canal", "candidat", "capable",
    "capital", "captiver", "caractere", "caresse", "carte", "casque", "casser", "cause",
    "celebre", "cellule", "cendre", "central", "centre", "cercle", "ceremonie", "certain",
    "cerveau", "cesser", "chaine", "chaise", "chaleur", "chambre", "champion", "chance",
    "changer", "chanson", "chanter", "chapitre", "charger", "charme", "chasse", "chateau",
    "chaud", "chef", "chemin", "chemise", "chercher", "cheval", "cheveux", "chien",
    "chiffre", "chimie", "chinois", "choisir", "choix", "chose", "cible", "cinema",
    "circuit", "circuler", "citoyen", "civil", "clair", "classe", "clef", "client",
    "climat", "clore", "coeur", "coin", "colere", "colline", "combat", "combien",
    "combler", "comedie", "comite", "commander", "comme", "commencer", "commerce", "commun",
    "comparer", "competent", "complet", "composer", "comprendre", "compte", "compter", "concept",
    "concert", "conclure", "concours", "condition", "conduire", "confier", "confirmer", "conflit",
    "connaitre", "conquete", "conseil", "consentir", "conserver", "considerer", "consister", "console",
    "constant", "constater", "construire", "contacter", "contenir", "content", "contexte", "continuer",
    "contrat", "contre", "controler", "convaincre", "convenir", "copain", "copie", "coquet",
    "corde", "corps", "corriger", "costume", "coter", "couche", "couler", "couleur",
    "coup", "couper", "couple", "courage", "courant", "courir", "cours", "course",
    "court", "couter", "couvrir", "craindre", "createur", "creer", "creuser", "crier",
    "crime", "crise", "critiquer", "croire", "croiser", "cuisine", "culture", "curieux",
    "danger", "danser", "debat", "deborder", "debout", "debut", "decembre", "decevoir",
    "dechirer", "decider", "declaration", "declarer", "decor", "decouvrir", "decrire", "dedans",
    "defaut", "defendre", "definir", "degager", "degre", "dehors", "dejeuner", "delai",
    "demain", "demander", "demarche", "demarrer", "demeurer", "demi", "denoncer", "dent",
    "depart", "depasser", "dependre", "depenser", "deplacer", "deposer", "depuis", "dernier",
    "derriere", "desir", "desirer", "desormais", "dessous", "dessus", "detail", "detendre",
    "detenir", "determiner", "detruire", "dette", "deuil", "devant", "devenir", "deviner",
    "devoir", "dialogue", "diamant", "dicter", "dieu", "different", "digne", "dimension",
    "diminuer", "dire", "direct", "diriger", "discours", "discret", "discuter", "disposer",
    "disputer", "distance", "distinguer", "divers", "diviser", "divorce", "docteur", "document",
    "doigt", "domaine", "dominer", "dommage", "donner", "dormir", "dossier", "double",
    "douche", "douleur", "doute", "douter", "doux", "drame", "dresser", "droit",
    "drole", "duree", "durer", "ecart", "echanger", "echapper", "echec", "echelle",
    "eclairer", "eclater", "ecole", "ecouter", "ecrire", "editeur", "education", "effet",
    "effectuer", "effort", "egal", "egard", "eglise", "election", "element", "eleve",
    "elever", "eliminer", "elle", "eloigner", "embarquer", "embrasser", "emotion", "empecher",
    "empire", "emploi", "employer", "emporter", "emprunter", "encadrer", "enceinte", "encore",
    "endroit", "energie", "enfance", "enfermer", "enfin", "engager", "enlever", "ennemi",
    "ennui", "ennuyer", "enorme", "enquete", "enseigner", "ensemble", "ensuite", "entendre",
    "entier", "entourer", "entrainer", "entre", "entree", "entreprendre", "entrer", "enveloppe",
    "envie", "environ", "envoyer", "epais", "epaule", "epoque", "epreuve", "equilibre",
    "equipe", "erreur", "escalier", "espace", "espece", "esperer", "espoir", "esprit",
    "essai", "essence", "essentiel", "essayer", "estimer", "etablir", "etage", "etat",
    "etendre", "eternel", "etoile", "etonner", "etrange", "etranger", "etroit", "etude",
    "etudier", "euro", "evaluer", "evenement", "eventuel", "evident", "eviter", "evoquer",
    "exact", "examen", "examiner", "excellent", "excepter", "exces", "exciter", "excuse",
    "excuser", "executer", "exemple", "exiger", "existence", "exister", "expert", "expliquer",
    "exploiter", "explorer", "exposer", "exprimer", "exterieur", "extreme", "fabrique", "fabuleux",
    "face", "facile", "facon", "facteur", "faible", "faim", "faire", "falloir",
    "famille", "fameux", "fantaisie", "fatigue", "fatiguer", "faute", "fauteuil", "faveur",
    "favori", "fecond", "femme", "fenetre", "ferme", "fermer", "fete", "feuille",
    "fiction", "fidele", "fier", "figure", "fille", "film", "fils", "final",
    "finance", "finir", "fixer", "flamme", "fleur", "fleuve", "foi", "fois",
    "folie", "fonction", "fond", "fonder", "fondre", "force", "forcer", "foret",
    "forme", "former", "formule", "fort", "fortune", "fosse", "fou", "foudre",
    "foule", "four", "fournir", "foyer", "frais", "franc", "francais", "frapper",
    "frere", "froid", "fromage", "front", "fruit", "fuir", "fumee", "fumer",
    "fusil", "futur", "gagner", "galerie", "garantir", "garcon", "garder", "gare",
    "gauche", "geler", "general", "genereux", "genie", "genre", "gens", "gentil",
    "geste", "glace", "glisser", "gloire", "gorge", "gout", "gouter", "grace",
    "grain", "grand", "grave", "grec", "greve", "grimper", "gris", "gros",
    "groupe", "guerre", "guider", "habitant", "habiter", "habituer", "haine", "hasard",
    "haut", "hauteur", "herbe", "heritage", "heros", "hesiter", "heure", "heureux",
    "hier", "histoire", "hiver", "homme", "honneur", "honte", "hopital", "horizon",
    "horrible", "hors", "hotel", "humain", "humeur", "humour", "ideal", "idee",
    "identifier", "identite", "ignorer", "ile", "illusion", "image", "imaginer", "immediat",
    "immense", "importer", "imposer", "impression", "imputer", "inciter", "inclure", "inconnu",
    "indiquer", "individu", "inferieur", "infini", "informer", "injuste", "innocent", "inquieter",
    "inscrire", "insister", "installer", "instant", "instaurer", "integrer", "intense", "intention",
    "interdire", "interesser", "interet", "internet", "interroger", "intervenir", "intime", "introduire",
    "inutile", "inventer", "inverse", "investir", "inviter", "isoler", "italien", "jamais",
    "jambe", "janvier", "jardin", "jaune", "jeter", "jeu", "jeudi", "jeune",
    "joie", "joindre", "joli", "joue", "jouer", "joueur", "jour", "journal",
    "juge", "juger", "juin", "juillet", "jupe", "jurer", "jusque", "juste",
    "justice", "justifier", "lac", "lacher", "laine", "laisser", "lancer", "langage",
    "langue", "large", "largeur", "laver", "lecon", "lecteur", "lecture", "leger",
    "lendemain", "lentement", "lettre", "lever", "levre", "liaison", "liberer", "liberte",
    "libre", "lien", "lier", "lieu", "ligne", "limite", "limiter", "linge",
    "liquide", "lire", "liste", "lit", "livre", "livrer", "local", "logement",
    "loger", "logique", "loi", "loin", "long", "longtemps", "louer", "lourd",
    "lumiere", "lundi", "lune", "lunettes", "lutte", "lutter", "luxe", "machine",
    "magasin", "magie", "magnifique", "mai", "main", "maintenir", "maire", "mais",
    "maison", "maitre", "majeur", "majorite", "mal", "malade", "maladie", "male",
    "malgre", "malheur", "manche", "manger", "manier", "maniere", "manifester", "manquer",
    "manteau", "marbre", "marchand", "marche", "marcher", "mardi", "marge", "mari",
    "mariage", "marier", "marquer", "mars", "masse", "matiere", "matin", "mauvais",
    "mecanisme", "medecin", "meilleur", "melanger", "meler", "membre", "memoire", "menacer",
    "menace", "mener", "mensonge", "mental", "mentir", "mepris", "mer", "merci",
    "mercredi", "mere", "merite", "merveille", "message", "mesure", "mesurer", "metal",
    "methode", "metier", "metre", "mettre", "meuble", "midi", "mieux", "milieu",
    "militaire", "mille", "million", "mince", "mine", "ministre", "minorite", "minute",
    "miracle", "miroir", "mise", "misere", "mission", "mobile", "mode", "modele",
    "moderne", "modifier", "moindre", "mois", "moitie", "moment", "monde", "mondial",
    "monnaie", "monsieur", "montagne", "monter", "montrer", "morale", "morceau", "mordre",
    "mort", "moteur", "motif", "mourir", "mouvement", "moyen", "multiple", "mur",
    "muscle", "musee", "musique", "mystere", "nager", "naissance", "naitre", "nation",
    "national", "nature", "naturel", "navire", "negatif", "neige", "nerveux", "net",
    "neuf", "neveu", "niveau", "noble", "noir", "nom", "nombre", "nombreux",
    "nommer", "nord", "normal", "note", "noter", "notion", "notre", "nourrir",
    "nouveau", "nouvelle", "novembre", "noyau", "nuage", "nuit", "numero", "objet",
    "obliger", "observer", "obstacle", "obtenir", "occasion", "occuper", "ocean", "octobre",
    "odeur", "oeil", "oeuvre", "offenser", "office", "officiel", "officier", "offre",
    "offrir", "oiseau", "ombre", "oncle", "opera", "opinion", "opposer", "option",
    "or", "orage", "orange", "orchestre", "ordinaire", "ordre", "oreille", "organe",
    "organiser", "origine", "original", "oser", "oter", "oublier", "ouest", "outil",
    "outre", "ouvrage", "ouvrier", "ouvrir", "page", "pain", "paix", "palais",
    "panne", "papier", "paquet", "paradis", "paraitre", "parcourir", "parent", "parfait",
    "parfois", "parfum", "parier", "parking", "parler", "parmi", "paroi", "parole",
    "part", "partager", "partenaire", "parti", "participer", "partie", "partir", "partout",
    "parvenir", "pas", "passage", "passer", "passion", "patience", "patron", "pauvre",
    "payer", "pays", "paysage", "paysan", "peau", "peche", "peindre", "peine",
    "pelouse", "pencher", "pendant", "penetrer", "penser", "penseur", "pension", "pente",
    "perdre", "pere", "periode", "permettre", "personne", "personnel", "perte", "peser",
    "petit", "peu", "peuple", "peur", "phrase", "physique", "piece", "pied",
    "piege", "pierre", "pile", "pilote", "pire", "piscine", "place", "placer",
    "plafond", "plage", "plaindre", "plaine", "plaire", "plaisir", "plan", "planche",
    "planter", "plaque", "plat", "plateau", "plein", "pleurer", "pleuvoir", "pluie",
    "plume", "plupart", "plus", "plusieurs", "plutot", "poche", "poeme", "poesie",
    "poete", "poids", "point", "pointe", "poing", "poire", "poisson", "poitrine",
    "police", "politique", "pomme", "pont", "populaire", "port", "porte", "porter",
    "portrait", "poser", "positif", "position", "posseder", "possible", "poste", "pot",
    "poule", "pour", "pourquoi", "poursuivre", "pourtant", "pousser", "pouvoir", "pratique",
    "pratiquer", "preceder", "precieux", "precis", "preciser", "preferer", "premier", "prendre",
    "preparer", "presence", "present", "presenter", "preserver", "presque", "presser", "pret",
    "pretendre", "preter", "preuve", "prevenir", "prevoir", "prier", "priere", "prince",
    "principe", "prison", "prive", "prix", "probleme", "proceder", "prochain", "proche",
    "produire", "produit", "professeur", "profit", "profiter", "profond", "programme", "progres",
    "projet", "prolonger", "promenade", "promener", "promesse", "promettre", "prononcer", "propos",
    "proposer", "propre", "propriete", "proteger", "prouver", "province", "provoquer", "prudent",
    "public", "publier", "puis", "puissance", "puissant", "punir", "pur", "qualifier",
    "qualite", "quand", "quantite", "quart", "quartier", "quelconque", "quelque", "querelle",
    "question", "questionner", "queue", "quitter", "quoi", "racine", "raconter", "radio",
    "raison", "raisonnable", "ramasser", "ramener", "rang", "ranger", "rapide", "rappeler",
    "rapport", "rapporter", "rapprocher", "rare", "raser", "rassembler", "rassurer", "rater",
    "rayon", "reaction", "reagir", "realiser", "realite", "recevoir", "rechercher", "recit",
    "reclamer", "recolte", "recommander", "recompense", "reconnaitre", "recours", "recouvrir", "recueillir",
    "reculer", "rediger", "redouter", "reduire", "refaire", "reflechir", "reflet", "refleter",
    "reforme", "refuser", "regard", "regarder", "regime", "region", "regle", "regler",
    "regner", "regret", "regretter", "regulier", "rein", "rejeter", "rejoindre", "relation",
    "relever", "relier", "religieux", "religion", "remarquer", "remercier", "remettre", "remonter",
    "remplacer", "remplir", "remporter", "remuer", "rencontrer", "rendre", "renoncer", "renouveler",
    "rentrer", "renverser", "renvoyer", "repandre", "reparer", "repas", "repasser", "repeter",
    "replique", "repliquer", "repondre", "reponse", "repos", "reposer", "repousser", "reprendre",
    "representant", "representer", "reproche", "reprocher", "republique", "reserve", "reserver", "residence",
    "resister", "resolution", "resoudre", "respect", "respecter", "respirer", "responsable", "ressembler",
    "ressentir", "ressource", "reste", "rester", "resultat", "resulter", "retablir", "retard",
    "retenir", "retirer", "retour", "retourner", "retrouver", "reunion", "reunir", "reussir",
    "reve", "reveil", "reveiller", "reveler", "revendication", "revenir", "rever", "revetir",
    "revoir", "revolution", "riche", "richesse", "rideau", "rien", "rigoureux", "rire",
    "risque", "risquer", "rivage", "rival", "riviere", "robe", "rocher", "roi",
    "role", "roman", "rompre", "rond", "rose", "roue", "rouge", "rouler",
    "route", "royaume", "rue", "ruine", "ruiner", "rythme", "sable", "sac",
    "sacre", "sage", "sagesse", "sain", "saint", "saisir", "saison", "salaire",
    "sale", "salle", "saluer", "salut", "samedi", "sang", "sante", "satisfaction",
    "satisfaire", "sauf", "sauter", "sauver", "savoir", "scandale", "scene", "science",
    "sec", "secret", "secteur", "securite", "seduire", "seigneur", "sein", "sejour",
    "selon", "semaine", "semblable", "sembler", "semer", "sens", "sensible", "sentier",
    "sentiment", "sentir", "separer", "septembre", "serieux", "serment", "serpent", "serrer",
    "service", "servir", "seul", "seulement", "severe", "sexe", "siecle", "siege",
    "sien", "signal", "signe", "signer", "signifier", "silence", "silencieux", "simple",
    "simplement", "sinon", "site", "situer", "six", "ski", "social", "societe",
    "soeur", "soi", "soie", "soif", "soigner", "soin", "soir", "soiree",
    "sol", "soldat", "soleil", "solide", "solidite", "solliciter", "solution", "sombre",
    "somme", "sommeil", "sommet", "sommettre", "son", "songer", "sonner", "sort",
    "sorte", "sortir", "sot", "sou", "souci", "soudain", "souffler", "souffrance",
    "souffrir", "souhaiter", "soulever", "souligner", "soumettre", "soupcon", "soupe", "source",
    "sourd", "sourire", "sous", "soutenir", "souvenir", "souvent", "spectacle", "sport",
    "stable", "stade", "station", "statut", "style", "subir", "succeder", "succes",
    "sucre", "sud", "suffire", "suffisant", "suggerer", "suisse", "suite", "suivant",
    "suivre", "sujet", "superieur", "supporter", "supposer", "supprimer", "sur", "surface",
    "surprendre", "surprise", "surtout", "surveiller", "survivre", "symbole", "sympathie", "systeme",
    "table", "tableau", "tache", "taille", "taire", "talent", "tandis", "tant",
    "tante", "tapis", "tard", "tarder", "tas", "tasse", "taux", "technique",
    "tel", "telephone", "tellement", "temoignage", "temoin", "temperature", "temps", "tendre",
    "tendresse", "tenir", "tenter", "terme", "terminer", "terrain", "terre", "terreur",
    "territoire", "tete", "texte", "theatre", "theme", "theorie", "tiers", "tige",
    "timbre", "timide", "tirer", "tiroir", "tissu", "titre", "toi", "toile",
    "toilette", "toit", "tolerance", "tomber", "ton", "tonnerre", "tort", "tot",
    "total", "toucher", "toujours", "tour", "tourner", "tourniquet", "tout", "trace",
    "tracer", "tradition", "traditionnel", "traduire", "trahir", "train", "trainer", "trait",
    "traitement", "traiter", "trajet", "tranquille", "transformer", "transmettre", "transparent", "travail",
    "travailler", "travailleur", "travers", "traverser", "trembler", "trente", "tres", "tresor",
    "triangle", "tribunal", "triste", "tromper", "trop", "trou", "trouble", "troubler",
    "trouver", "tuer", "type", "unique", "unite", "univers", "universel", "urgent",
    "usage", "user", "usine", "utile", "utiliser", "vacances", "vague", "vaincre",
    "valable", "valeur", "valoir", "vaste", "veille", "veiller", "veine", "vendeur",
    "vendre", "venir", "vent", "vente", "ventre", "veritable", "verite", "verre",
    "vers", "verser", "vert", "vertu", "vetement", "viande", "victime", "victoire",
    "vide", "vider", "vie", "vieillard", "vieillir", "vieux", "vif", "vigne",
    "village", "ville", "vin", "vingt", "violence", "violent", "violet", "virage",
    "visage", "viser", "visible", "vision", "visite", "visiter", "visiteur", "vitesse",
    "vitre", "vivant", "vivre", "voeu", "voici", "voie", "voila", "voir",
    "voisin", "voiture", "voix", "vol", "voler", "volonte", "volume", "voter",
    "vouloir", "voyage", "voyager", "voyageur", "vrai", "vraiment", "vue", "zero",
    "zone",
    
    # Mots courts (3-5 lettres)
    "abeille", "abord", "abri", "acte", "adieu", "age", "aide", "aile",
    "air", "aise", "ami", "amie", "amour", "an", "ane", "ange",
    "ans", "appui", "arc", "arme", "art", "as", "astre", "aube",
    "au", "aux", "avec", "avis", "axe", "bain", "bal", "banc",
    "bar", "bas", "base", "beau", "bec", "bete", "beton", "bien",
    "bilan", "bille", "bis", "blanc", "ble", "bleu", "bloc", "boeuf",
    "bois", "bon", "bond", "bonne", "bonte", "bord", "bosse", "bot",
    "bout", "bras", "bref", "brick", "bruit", "brut", "but", "cadre",
    "cafe", "cage", "cake", "camp", "cap", "car", "cas", "cave",
    "ceci", "cela", "cent", "ceux", "chair", "champ", "chant", "char",
    "chat", "cher", "chez", "choc", "chute", "ciel", "clair", "clan",
    "clef", "clin", "code", "coin", "col", "colle", "colon", "compte",
    "conte", "coq", "cor", "corne", "corps", "cote", "cou", "coup",
    "cour", "cours", "court", "creme", "cri", "crime", "crise", "croix",
    "cru", "cube", "cycle", "dame", "dans", "date", "debut", "deces",
    "decor", "defi", "degre", "delai", "delta", "demi", "depuis", "des",
    "desir", "destin", "dette", "deuil", "deux", "dire", "dix", "don",
    "donc", "dont", "dos", "doux", "drame", "drap", "droit", "duc",
    "duo", "dur", "dure", "eau", "echo", "eclat", "edit", "effet",
    "ego", "elle", "eloge", "email", "emoi", "en", "encre", "enfant",
    "enjeu", "envie", "epee", "ere", "erre", "essor", "est", "et",
    "ete", "etre", "euro", "eux", "exces", "face", "fait", "fame",
    "faute", "faux", "fer", "ferme", "fete", "feu", "feuille", "fibre",
    "fil", "fille", "film", "fils", "fin", "fixe", "flanc", "fleur",
    "flot", "flux", "foi", "fois", "folie", "fond", "font", "force",
    "foret", "forme", "fort", "forum", "fosse", "fou", "foule", "four",
    "frais", "franc", "front", "fruit", "fumee", "fur", "fusil", "gain",
    "gant", "garde", "gare", "gaz", "gel", "gene", "genie", "genre",
    "gens", "geste", "gilet", "glace", "gout", "grace", "grain", "grand",
    "gras", "grave", "grec", "gris", "gros", "groupe", "guerre", "guide",
    "haine", "hall", "hasard", "haut", "herbe", "heros", "heure", "hier",
    "homme", "honneur", "honte", "hotel", "huit", "hymne", "ideal", "idee",
    "ile", "image", "index", "infini", "instant", "issue", "jambe", "jeu",
    "jeudi", "jeune", "joie", "joue", "jour", "juge", "jus", "juste",
    "lac", "laid", "laine", "lait", "lance", "large", "laser", "latin",
    "lent", "leur", "lever", "levre", "libre", "lien", "lieu", "ligne",
    "lin", "lion", "liste", "lit", "litre", "livre", "local", "loi",
    "loin", "long", "lot", "lourd", "lui", "lutte", "luxe", "ma",
    "main", "mais", "mal", "male", "maman", "mardi", "marge", "mari",
    "marin", "mars", "masse", "matin", "maxi", "media", "mer", "mere",
    "mes", "metal", "metre", "mets", "mi", "midi", "mien", "mieux",
    "milieu", "mille", "mine", "mini", "mise", "mode", "moi", "moine",
    "moins", "mois", "monde", "mont", "moral", "mort", "mot", "motif",
    "moto", "mou", "moule", "moyen", "mur", "musee", "mythe", "nage",
    "nappe", "nerf", "net", "neuf", "nez", "ni", "nid", "noble",
    "noeud", "noir", "nom", "non", "nord", "norme", "nos", "note",
    "notre", "nous", "noyer", "nu", "nuage", "nuit", "nul", "objet",
    "ocean", "odeur", "oeil", "oeuf", "oeuvre", "offre", "oh", "on",
    "oncle", "onde", "onze", "opera", "or", "oral", "orange", "ordre",
    "orgue", "os", "oser", "ote", "ou", "ouest", "oui", "ours",
    "outil", "ouvert", "paie", "pain", "pair", "paix", "palais", "pan",
    "pape", "par", "parc", "parent", "pari", "paroi", "part", "parti",
    "pas", "passe", "pate", "patron", "pause", "pave", "pays", "peau",
    "peine", "pelle", "pente", "per", "pere", "perle", "permis", "perte",
    "peur", "phase", "photo", "piano", "pic", "piece", "pied", "pieu",
    "pile", "pin", "pion", "piste", "place", "plage", "plain", "plan",
    "plant", "plat", "plein", "pli", "plomb", "pluie", "plus", "pneu",
    "poche", "poeme", "poete", "poids", "poing", "point", "poire", "pois",
    "polar", "pole", "poli", "pomme", "pompe", "pont", "pope", "porc",
    "port", "porte", "pose", "poste", "pot", "pouce", "poule", "pour",
    "poutre", "prix", "proche", "profit", "projet", "promo", "propos", "prose",
    "puce", "puit", "pur", "pure", "quai", "quand", "quart", "que",
    "quel", "queue", "qui", "quoi", "quota", "race", "radar", "radio",
    "rage", "raid", "rail", "rang", "rare", "rat", "rayon", "rebut",
    "recit", "recul", "refus", "regle", "reine", "rein", "relais", "remis",
    "repas", "repos", "res", "reste", "reve", "revue", "rez", "riche",
    "rien", "rime", "ring", "rire", "rite", "rival", "rive", "riz",
    "robe", "robot", "roche", "roi", "role", "roman", "rond", "rose",
    "rouge", "route", "ru", "rue", "ruine", "rural", "ruse", "sable",
    "sac", "sage", "saint", "salle", "salut", "samedi", "sang", "sante",
    "sauce", "sauf", "saule", "saut", "scene", "scie", "score", "sec",
    "seize", "sel", "selon", "sens", "sept", "serie", "seul", "seuil",
    "sexe", "short", "si", "sien", "siege", "signe", "silence", "silo",
    "simple", "site", "six", "ski", "sobre", "social", "soeur", "soi",
    "soie", "soif", "soin", "soir", "sol", "sole", "soleil", "somme",
    "son", "sonde", "songe", "sort", "sot", "sou", "souci", "soupe",
    "sous", "sport", "stade", "stand", "star", "stock", "stop", "store",
    "style", "su", "succès", "sucre", "sud", "sueur", "suie", "suite",
    "sujet", "super", "sur", "ta", "table", "tache", "tact", "taille",
    "taire", "talus", "tant", "tante", "tapis", "tard", "tarte", "tas",
    "tasse", "taux", "taxi", "te", "tel", "temps", "tenir", "tennis",
    "terme", "terre", "test", "tete", "texte", "theme", "these", "ticket",
    "tien", "tige", "tir", "tirage", "titre", "toi", "toile", "toit",
    "ton", "tonne", "tort", "tot", "total", "tour", "tout", "trace",
    "tract", "train", "trait", "trajet", "trame", "treve", "tri", "trio",
    "trois", "tronc", "trop", "trou", "truc", "tube", "tuile", "type",
    "un", "une", "uni", "unite", "urban", "urgent", "us", "usage",
    "usine", "utile", "vache", "vague", "vain", "valeur", "valoir", "vas",
    "vaste", "veau", "vecu", "veille", "veine", "velo", "vendre", "venir",
    "vent", "ventre", "ver", "verbe", "verre", "vers", "vert", "vertu",
    "veste", "vetir", "viande", "vice", "vide", "vie", "vieux", "vif",
    "vigne", "ville", "vin", "vingt", "visa", "viser", "visite", "vite",
    "vitre", "vivant", "vivre", "voeu", "voie", "voila", "voir", "voisin",
    "voiture", "voix", "vol", "voler", "voleur", "vote", "voter", "votre",
    "vous", "voyage", "vrai", "vue", "wagon", "web", "week", "yacht",
    "yoga", "zone", "zoo"
]

# Nettoyer et préparer la liste (enlever accents pour la recherche, garder originaux pour affichage)
def normalize_word(word):
    """Normalise un mot en majuscules sans accents pour la comparaison"""
    replacements = {
        'é': 'E', 'è': 'E', 'ê': 'E', 'ë': 'E',
        'à': 'A', 'â': 'A', 'ä': 'A',
        'ù': 'U', 'û': 'U', 'ü': 'U',
        'ô': 'O', 'ö': 'O',
        'î': 'I', 'ï': 'I',
        'ç': 'C',
        'œ': 'OE', 'æ': 'AE'
    }
    result = word.upper()
    for old, new in replacements.items():
        result = result.replace(old.upper(), new).replace(old, new)
    return result

# Créer un dictionnaire avec mots normalisés comme clés
WORDS_DICT = {}
for word in FRENCH_WORDS:
    normalized = normalize_word(word)
    if normalized not in WORDS_DICT:
        WORDS_DICT[normalized] = word

# Liste triée par longueur décroissante pour la recherche
WORDS_BY_LENGTH = sorted(WORDS_DICT.keys(), key=lambda x: -len(x))

def get_words_list():
    """Retourne la liste des mots normalisés triés par longueur décroissante"""
    return WORDS_BY_LENGTH.copy()

def get_original_word(normalized):
    """Retourne le mot original avec accents"""
    return WORDS_DICT.get(normalized, normalized)
